[package]
name = "buildsystem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.41", features = ["backtrace"] }
clap = { version = "4.4.1", features = ["derive"] }
fs-err = "2.8.1"
