name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # This doesn't seem to work.
    # - name: Install Linux and Windows Cross Compilers
    #   uses: awalsh128/cache-apt-pkgs-action@latest
    #   with:
    #     # There's a -posix version of gcc-mingw. It just affects whether
    #     # C++ threading features are supported but we don't need that.
    #     # https://stackoverflow.com/a/30390278
    #     packages: musl-tools gcc-mingw-w64-x86-64-win32
    #     version: 1.0

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    # This compiles Clang but it should cache the results for future builds.
    - name: Set up MacOS Cross Compiler
      uses: Timmmm/setup-osxcross@v3
      with:
        osx-version: "12.3"

    - name: Install Rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu x86_64-apple-darwin aarch64-apple-darwin

    - name: Check out source code
      uses: actions/checkout@v4

    - name: Make Release
      run: ./make release

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: '*.vsix'
