name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux and Windows Cross Compilers
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        # There's a -posix version of gcc-mingw. It just affects whether
        # C++ threading features are supported but we don't need that.
        # https://stackoverflow.com/a/30390278
        packages: musl-tools gcc-mingw-w64-x86-64-win32
        version: 1.0

    # This builds Clang from source and doesn't seem to cache it.
    # - name: Set up MacOS Cross Compiler
    #   uses: mbround18/setup-osxcross@v1
    #   with:
    #     osx-version: "12.3"

    - name: Install Musl
      run: rustup target add x86_64-unknown-linux-musl

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Make Release
      run: ./make release
